import House from "@/models/House";

const houses: House[] = [
  {
    id: 1,
    name: "Greenwood Residence",
    description: "A cozy modern house surrounded by lush greenery.",
    location: "Jakarta Selatan, Indonesia",
    facilities: ["WiFi", "AC", "Parking", "Laundry"],
    type: "kost putra",
    images: ["/images/house1a.jpg", "/images/house1b.jpg"],
    managerId: 2,
    ownerId: 1,
    status: "available",
    createdAt: "2025-10-01T10:00:00Z",
    updatedAt: "2025-10-05T14:00:00Z",
    pricePerMonth: 500000,
  },
  {
    id: 2,
    name: "Blue Horizon Kost",
    description: "Affordable room near campus with complete facilities.",
    location: "Depok, Indonesia",
    facilities: ["WiFi", "Shared Kitchen", "Laundry"],
    type: "kost campur",
    images: ["/images/house2a.jpg", "/images/house2b.jpg"],
    managerId: 3,
    ownerId: 1,
    status: "available",
    createdAt: "2025-09-28T09:00:00Z",
    updatedAt: "2025-10-01T11:00:00Z",
    pricePerMonth: 780000,
  },
  {
    id: 3,
    name: "Sunrise Kost",
    description: "Clean and quiet environment perfect for students.",
    location: "Surabaya, Indonesia",
    facilities: ["WiFi", "AC", "CCTV"],
    type: "kost putri",
    images: ["/images/house3a.jpg", "/images/house3b.jpg"],
    managerId: 4,
    ownerId: 2,
    status: "available",
    createdAt: "2025-09-25T08:00:00Z",
    updatedAt: "2025-09-30T15:00:00Z",
    pricePerMonth: 1200000,
  },
  {
    id: 4,
    name: "Central City Kost",
    description: "Located in the heart of the city, close to public transport.",
    location: "Bandung, Indonesia",
    facilities: ["WiFi", "Hot Water", "Laundry"],
    type: "kost putri",
    images: ["/images/house4a.jpg", "/images/house4b.jpg"],
    managerId: 5,
    ownerId: 2,
    status: "occupied",
    createdAt: "2025-09-22T12:00:00Z",
    updatedAt: "2025-10-02T10:00:00Z",
    pricePerMonth: 560000,
  },
  {
    id: 5,
    name: "Kost Merah Putih",
    description: "Spacious rooms with complete amenities.",
    location: "Yogyakarta, Indonesia",
    facilities: ["WiFi", "AC", "Parking", "Kitchen"],
    type: "kost putra",
    images: ["/images/house5a.jpg", "/images/house5b.jpg"],
    managerId: 3,
    ownerId: 1,
    status: "available",
    createdAt: "2025-09-20T10:00:00Z",
    updatedAt: "2025-09-25T18:00:00Z",
    pricePerMonth: 488000,
  },
  {
    id: 6,
    name: "UrbanStay Kost",
    description: "Modern-style kost with minimalist design.",
    location: "Bekasi, Indonesia",
    facilities: ["WiFi", "Parking", "CCTV"],
    type: "kost campur",
    images: ["/images/house6a.jpg", "/images/house6b.jpg"],
    managerId: 4,
    ownerId: 2,
    status: "available",
    createdAt: "2025-09-18T14:00:00Z",
    updatedAt: "2025-09-21T12:00:00Z",
    pricePerMonth: 650000,
  },
  {
    id: 7,
    name: "Harmony Kost",
    description: "Peaceful kost with spacious shared areas.",
    location: "Malang, Indonesia",
    facilities: ["WiFi", "Laundry", "Kitchen"],
    type: "kost putri",
    images: ["/images/house7a.jpg", "/images/house7b.jpg"],
    managerId: 6,
    ownerId: 3,
    status: "occupied",
    createdAt: "2025-09-15T08:30:00Z",
    updatedAt: "2025-09-20T14:00:00Z",
    pricePerMonth: 780000,
  },
  {
    id: 8,
    name: "Campus Edge Kost",
    description: "Only 5 minutes walking to the university gate.",
    location: "Depok, Indonesia",
    facilities: ["WiFi", "Laundry", "Shared Kitchen"],
    type: "kost putra",
    images: ["/images/house8a.jpg", "/images/house8b.jpg"],
    managerId: 2,
    ownerId: 1,
    status: "available",
    createdAt: "2025-09-10T10:00:00Z",
    updatedAt: "2025-09-18T09:00:00Z",
    pricePerMonth: 666666,
  },
  {
    id: 9,
    name: "Comfort Kost",
    description: "Affordable and quiet place for students.",
    location: "Semarang, Indonesia",
    facilities: ["WiFi", "AC", "CCTV", "Laundry"],
    type: "kost putra",
    images: ["/images/house9a.jpg", "/images/house9b.jpg"],
    managerId: 3,
    ownerId: 1,
    status: "occupied",
    createdAt: "2025-09-07T09:30:00Z",
    updatedAt: "2025-09-14T11:00:00Z",
    pricePerMonth: 555555,
  },
  {
    id: 10,
    name: "Ocean View Kost",
    description: "Enjoy sea breeze and modern facilities.",
    location: "Bali, Indonesia",
    facilities: ["WiFi", "Parking", "Laundry"],
    type: "kost campur",
    images: ["/images/house10a.jpg", "/images/house10b.jpg"],
    managerId: 7,
    ownerId: 3,
    status: "available",
    createdAt: "2025-09-05T13:00:00Z",
    updatedAt: "2025-09-11T16:00:00Z",
    pricePerMonth: 777000,
  },
];

export default houses;
